---
- name: Linux Security Baseline
  hosts: servers
  become: yes
  gather_facts: yes

  tasks:
    - name: Install UFW firewall
      apt:
        name: ufw
        state: present
      tags: firewall

    - name: Configure firewall defaults
      ufw:
        state: enabled
        policy: deny
      tags: firewall

    - name: Allow SSH with rate limiting
      ufw:
        rule: limit
        port: ssh
      tags: firewall

    - name: Ensure LightDM is installed
      apt:
        name: lightdm
        state: present
        update_cache: yes
      tags: hardening

    - name: Check if LightDM config directory exists
      stat:
        path: /etc/lightdm
      register: lightdm_dir
      tags: hardening

    - name: Disable guest login if LightDM is installed
      lineinfile:
        path: /etc/lightdm/lightdm.conf
        regexp: '^allow-guest'
        line: 'allow-guest=false'
        create: yes
      when: lightdm_dir.stat.exists
      tags: hardening
